# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfQ-Qd2aaAeOHXB4-j2gTWiYTFvfKKu7
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

# URL for the Wine dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
column_names = ['Class', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash',
                'Magnesium', 'Total phenols', 'Flavanoids', 'Nonflavanoid phenols',
                'Proanthocyanins', 'Color intensity', 'Hue',
                'OD280/OD315 of diluted wines', 'Proline']

# Load the dataset
print("Loading Wine Dataset...")
df = pd.read_csv(url, names=column_names)

# Display dataset information
print(f"\nDataset shape: {df.shape}")
print(f"\nFirst 5 rows:")
#print(df.head())
print(f"\nClass distribution:")
print(df['Class'].value_counts())
print(f"\nBasic statistics:")
print(df.describe())

# Separate features and target
X = df.drop('Class', axis=1)
y = df['Class']

# Split the data into training (70%) and testing (30%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

print(f"\nTraining set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")
print(f"Number of features: {X_train.shape[1]}")

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import matplotlib.pyplot as plt
# ==================================================
# Training
# ==================================================
print("\n" + "="*60)
print("Training Random Forest")
print("="*60)

rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42
)

rf_model.fit(X_train, y_train)
svm_model=SVC(kernel='linear',random_state=42,C=1.0,probability=True)
svm_model.fit(X_train,y_train)



np.random.seed(42)  # For reproducibility
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Create visualizations for trees 1, 2, and 100
trees_to_show = [0, 1, 99]  # Python uses 0-based indexing
feature_names = X_train.columns.tolist()
class_names = ['No', 'Yes']
n_trees_range = range(10, 201)
oob_errors = [
    1 - RandomForestClassifier(n_estimators=n, oob_score=True, random_state=42).fit(X_train, y_train).oob_score_
    for n in n_trees_range
]

# Create a plot


# Print results at key intervals
print("OOB Error by Number of Trees:")
for i, error in enumerate(oob_errors, 1):
    if i % 10 == 0:
        print(f"Trees: {i:3d}, OOB Error: {error:.4f}")

final_model=RandomForestClassifier(
    n_estimators=40,
    random_state=42
)


final_model.fit(
    X_train,
    y_train
)
final_svm=svm_model.fit(X_train,y_train)

print("Training complete!")

# Predictions
y_pred = final_model.predict(X_test)
y_pred_proba = final_model.predict_proba(X_test)
y_pred_svm=final_svm.predict(X_test)
y_pred_proba_svm=final_svm.predict_proba(X_test)

# Metrics
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
accuracy_svm=accuracy_score(y_test,y_pred_svm)
conf_matrix_svm=confusion_matrix(y_test,y_pred_svm)
class_report_svm=classification_report(y_test,y_pred_svm)


# ==================================================
# Visualization
# ==================================================


# Feature importance graph

print("\nModel complete!")
print("\n" + "="*60)
print("RANDOM FOREST RESULTS")
print("="*60)
print(f"\nAccuracy: {accuracy:.4f} ({accuracy*100:.2f}%)")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)

print("\n" + "="*60)
print("SVM RESULTS")
print("="*60)
print(f"\nAccuracy: {accuracy_svm:.4f} ({accuracy_svm*100:.2f}%)")
print("\nConfusion Matrix:")
print(conf_matrix_svm)
print("\nClassification Report:")
print(class_report_svm)


# ==================================================
# Per-class analysis
# ==================================================

print("\n" + "="*60)
print("PER CLASS PERFORMANCE")
print("="*60)

per_class_accuracy = conf_matrix.diagonal()/conf_matrix.sum(axis=1)

for i, class_label in enumerate(rf_model.classes_):

    print(f"\nClass {class_label}")
    print(f"Accuracy: {per_class_accuracy[i]:.4f}")
    print(f"Correct: {conf_matrix[i,i]}")
    print(f"Total: {conf_matrix.sum(axis=1)[i]}")


plt.figure(figsize=(8,6))

plt.imshow(conf_matrix)

plt.title("Confusion Matrix")
plt.colorbar()

plt.xticks(
    range(len(rf_model.classes_)),
    rf_model.classes_
)

plt.yticks(
    range(len(rf_model.classes_)),
    rf_model.classes_
)

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()
# ==================================================
# Per-class analysis for SVM
# ==================================================

print("\n" + "="*60)
print("PER CLASS PERFORMANCE - SVM")
print("="*60)

per_class_accuracy_svm = (
    conf_matrix_svm.diagonal() /
    conf_matrix_svm.sum(axis=1)
)

for i, class_label in enumerate(final_svm.classes_):

    print(f"\nClass {class_label}")
    print(
        f"Accuracy: "
        f"{per_class_accuracy_svm[i]:.4f}"
    )

    print(
        f"Correct: "
        f"{conf_matrix_svm[i,i]}"
    )

    print(
        f"Total: "
        f"{conf_matrix_svm.sum(axis=1)[i]}"
    )


# ==================================================
# SVM Confusion Matrix Visualization
# ==================================================

plt.figure(figsize=(8,6))

plt.imshow(
    conf_matrix_svm,
    cmap='Blues'
)

plt.title("Confusion Matrix - SVM")

plt.colorbar()

plt.xticks(
    range(len(final_svm.classes_)),
    final_svm.classes_
)

plt.yticks(
    range(len(final_svm.classes_)),
    final_svm.classes_
)

plt.xlabel("Predicted")
plt.ylabel("Actual")


# Add values inside cells

for i in range(conf_matrix_svm.shape[0]):
    for j in range(conf_matrix_svm.shape[1]):

        plt.text(
            j,
            i,
            conf_matrix_svm[i,j],
            ha='center',
            va='center'
        )

plt.show()





from sklearn.model_selection import cross_val_score
# ==================================================
# Average confidence Random Forest
# ==================================================
avg_confidence = np.mean(
    np.max(y_pred_proba, axis=1)
)

print("\nAverage confidence:",
      f"{avg_confidence:.4f}")

# ==================================================
# Cross validation
# ==================================================

print("\n" + "="*60)
print("CROSS VALIDATION")
print("="*60)

cv_scores = cross_val_score(
    rf_model,
    X_train,
    y_train,
    cv=5
)

print("Scores:", cv_scores)
print(
    f"Mean:{cv_scores.mean():.4f}"
)
print(
    f"Std:{cv_scores.std():.4f}"
)

from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

# ==================================================
# Average confidence
# ==================================================

avg_confidence_svm = np.mean(
    np.max(y_pred_proba_svm, axis=1)
)

print(
    "\nAverage confidence:",
    f"{avg_confidence_svm:.4f}"
)

# ==================================================
# Cross validation
# ==================================================

print("\n" + "="*60)
print("SVM CROSS VALIDATION")
print("="*60)

cv_scores_svm = cross_val_score(
    svm_model,
    X_train,
    y_train,
    cv=5
)

print(
    "Scores:",
    cv_scores_svm
)

print(
    f"Mean:{cv_scores_svm.mean():.4f}"
)

print(
    f"Std:{cv_scores_svm.std():.4f}"
)

# ==================================================
# Hyperparameter comparison
# ==================================================

print("\n" + "="*60)
print("SVM PARAMETER COMPARISON")
print("="*60)

C_values = [0.01,0.1,1,10,100]

best_score_svm = 0
best_C = 0

print(
    f"{'C value':<10}{'CV Accuracy'}"
)

for c in C_values:

    temp_model = SVC(
        kernel='linear',
        C=c,
        probability=True,
        random_state=42
    )

    scores = cross_val_score(
        temp_model,
        X_train,
        y_train,
        cv=5
    )

    mean_score = scores.mean()

    print(
        f"{c:<10}{mean_score:.4f}"
    )

    if mean_score > best_score_svm:

        best_score_svm = mean_score
        best_C = c


print(
    f"\nBest C value: {best_C}"
)

# ==================================================
# Final model
# ==================================================

final_svm = SVC(
    kernel='linear',
    C=best_C,
    probability=True,
    random_state=42
)

final_svm.fit(
    X_train,
    y_train
)

final_accuracy_svm = accuracy_score(
    y_test,
    final_svm.predict(X_test)
)

print(
    f"\nFinal SVM Accuracy: "
    f"{final_accuracy_svm:.4f}"
)

# ==================================================
# Confusion Matrix Visualization
# ==================================================

from sklearn.inspection import permutation_importance
import matplotlib.pyplot as plt
# ==================================================
# Mean Decrease in Impurity (MDI)
# ==================================================

print("\n" + "="*60)
print("MEAN DECREASE IN IMPURITY (MDI)")
print("="*60)

mdi_importance = pd.DataFrame({
    'Feature': X.columns,
    'MDI Importance': rf_model.feature_importances_
})

mdi_importance = mdi_importance.sort_values(
    by='MDI Importance',
    ascending=False
)

print("\nMDI Feature Ranking:")
print(mdi_importance)

# Plot MDI
plt.figure(figsize=(10,6))

plt.bar(
    mdi_importance['Feature'],
    mdi_importance['MDI Importance']
)

plt.xticks(rotation=90)

plt.xlabel("Features")
plt.ylabel("Importance Score")

plt.title(
    "Mean Decrease in Impurity (Random Forest)"
)

plt.tight_layout()
plt.show()

print("\n" + "="*60)
print("PERMUTATION IMPORTANCE")
print("="*60)

perm_importance = permutation_importance(
    rf_model,
    X_test,
    y_test,
    n_repeats=10,
    random_state=42,
    scoring='accuracy'
)

perm_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance Mean': perm_importance.importances_mean,
    'Importance Std': perm_importance.importances_std
})

perm_df = perm_df.sort_values(
    by='Importance Mean',
    ascending=False
)

print("\nPermutation Importance Ranking:")
print(perm_df)

print("\nTop 5 Features (Permutation Importance):")

for _, row in perm_df.head(5).iterrows():
    print(
        f"{row['Feature']}: "
        f"{row['Importance Mean']:.4f} "
        f"(±{row['Importance Std']:.4f})"
    )

# Plot permutation importance

plt.figure(figsize=(10,6))

plt.bar(
    perm_df['Feature'],
    perm_df['Importance Mean']
)

plt.xticks(rotation=90)

plt.xlabel("Features")
plt.ylabel("Importance Score")

plt.title(
    "Permutation Importance"
)

plt.tight_layout()
plt.show()

print("\n" + "="*60)
print("FEATURE IMPORTANCE")
print("="*60)

importance_df = pd.DataFrame({
    'Feature':X.columns,
    'Importance':rf_model.feature_importances_
})

importance_df = importance_df.sort_values(
    by='Importance',
    ascending=False
)

print(importance_df)

print("\nTop 5 Features:")

for _, row in importance_df.head(5).iterrows():
    print(
        f"{row['Feature']} : "
        f"{row['Importance']:.4f}"
    )



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import (
    train_test_split,
    cross_val_score
)

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# ======================================================
# LOAD DATASET
# ======================================================

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"

column_names = [
    'Class','Alcohol','Malic acid','Ash',
    'Alcalinity of ash','Magnesium',
    'Total phenols','Flavanoids',
    'Nonflavanoid phenols',
    'Proanthocyanins',
    'Color intensity','Hue',
    'OD280/OD315 of diluted wines',
    'Proline'
]

df = pd.read_csv(url, names=column_names)
print(f"\nDataset shape: {df.shape}")
print(f"\nFirst 5 rows:")
print(df.head())
print(f"\nClass distribution:")
print(df['Class'].value_counts())
print(f"\nBasic statistics:")
print(df.describe())
print("Dataset shape:", df.shape)

X = df.drop("Class", axis=1)
y = df["Class"]

# ======================================================
# TRAIN TEST SPLIT
# ======================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

# ======================================================
# MODELS
# ======================================================

models = {

    "SVM":
    Pipeline([
        ('scaler', StandardScaler()),
        ('model',
         SVC(
             kernel='rbf',
             probability=True,
             random_state=42
         ))
    ]),

    "Random Forest":
    Pipeline([
        ('model',
         RandomForestClassifier(
             n_estimators=200,
             random_state=42
         ))
    ])
}

# ======================================================
# TRAIN + EVALUATE
# ======================================================

results=[]

for name, model in models.items():

    print("\n"+"="*60)
    print(name)
    print("="*60)

    model.fit(X_train,y_train)

    y_pred=model.predict(X_test)

    accuracy=accuracy_score(y_test,y_pred)

    cv_scores=cross_val_score(
        model,
        X_train,
        y_train,
        cv=5,
        scoring='accuracy'
    )

    results.append({
        'Model':name,
        'Accuracy':accuracy,
        'CV Mean':cv_scores.mean(),
        'CV Std':cv_scores.std()
    })

    print(f"\nTest Accuracy: {accuracy:.4f}")

    print(
        f"Cross Validation Accuracy: "
        f"{cv_scores.mean():.4f}"
        f" (+/- {cv_scores.std():.4f})"
    )

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test,y_pred))

    print("\nClassification Report:")
    print(classification_report(y_test,y_pred))

# ======================================================
# COMPARISON TABLE
# ======================================================

results_df=pd.DataFrame(results)

print("\n"+"="*70)
print("SVM vs RANDOM FOREST")
print("="*70)

print(results_df)

best_model=results_df.loc[
    results_df['Accuracy'].idxmax()
]

print("\nBest Model:")
print(best_model)

# ======================================================
# ACCURACY COMPARISON
# ======================================================

plt.figure(figsize=(8,5))

plt.bar(
    results_df["Model"],
    results_df["Accuracy"]
)

plt.xlabel("Model")
plt.ylabel("Accuracy")
plt.title("SVM vs Random Forest Accuracy")

plt.tight_layout()
plt.show()

# ======================================================
# CROSS VALIDATION COMPARISON
# ======================================================

plt.figure(figsize=(8,5))

plt.errorbar(
    results_df["Model"],
    results_df["CV Mean"],
    yerr=results_df["CV Std"],
    marker='o'
)

plt.xlabel("Model")
plt.ylabel("Cross Validation Accuracy")
plt.title("Cross Validation Comparison")

plt.tight_layout()
plt.show()

# ======================================================
# RANDOM FOREST FEATURE IMPORTANCE
# ======================================================

rf = models["Random Forest"]

feature_importance = (
    rf.named_steps['model']
    .feature_importances_
)

importance_df = pd.DataFrame({
    'Feature':X.columns,
    'Importance':feature_importance
})

importance_df=importance_df.sort_values(
    by='Importance',
    ascending=False
)

print("\nTop Features from Random Forest:")
print(importance_df.head(10))

plt.figure(figsize=(10,6))

plt.bar(
    importance_df['Feature'],
    importance_df['Importance']
)

plt.xticks(rotation=45)

plt.xlabel("Features")
plt.ylabel("Importance")
plt.title("Random Forest Feature Importance")

plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report,
    roc_auc_score, roc_curve
)

# -------------------------------
# 1. LOAD DATA
# -------------------------------
df = pd.read_csv('/content/sample_data/diabetes.csv')

# Convert target to categorical


# -------------------------------
# 2. HANDLE INVALID ZEROS
# -------------------------------
cols_with_zero = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_zero] = df[cols_with_zero].replace(0, np.nan)

# -------------------------------
# 3. CORRELATION ANALYSIS
# -------------------------------
plt.figure(figsize=(10,8))
corr = df.corr(numeric_only=True)

sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Feature Correlation Matrix")
plt.show()

print("\n🔍 Correlation with Outcome:")
print(corr['Outcome'].sort_values(ascending=False))

# -------------------------------
# 4. IMPUTATION
# -------------------------------
X = df.drop('Outcome', axis=1)
y = df['Outcome']

imputer = SimpleImputer(strategy='median')
X = imputer.fit_transform(X)

# -------------------------------
# 5. TRAIN-TEST SPLIT
# -------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

# -------------------------------
# 6. SCALING
# -------------------------------
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# -------------------------------
# 7. MODELS
# -------------------------------

# Logistic Regression (L2)
log_l2 = LogisticRegression(penalty='l2', max_iter=5000, class_weight='balanced')
log_l2.fit(X_train_scaled, y_train)

# Logistic Regression (L1)
log_l1 = LogisticRegression(penalty='l1', solver='liblinear', max_iter=5000)
log_l1.fit(X_train_scaled, y_train)

# KNN
k_values = range(1, 16)
knn_scores = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    knn_scores.append(knn.score(X_test_scaled, y_test))

best_k = k_values[np.argmax(knn_scores)]

knn_best = KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X_train_scaled, y_train)

# Naive Bayes
nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)

# -------------------------------
# 8. METRICS FUNCTION
# -------------------------------
def get_metrics(y_true, y_pred, y_prob, name):
    cm = confusion_matrix(y_true, y_pred)
    TN, FP, FN, TP = cm.ravel()

    sensitivity = TP / (TP + FN)
    specificity = TN / (TN + FP)

    return {
        'Model': name,
        'Accuracy': accuracy_score(y_true, y_pred),
        'Precision': precision_score(y_true, y_pred),
        'Sensitivity': sensitivity,
        'Specificity': specificity,
        'F1-Score': f1_score(y_true, y_pred),
        'ROC-AUC': roc_auc_score(y_true, y_prob)
    }

# -------------------------------
# 9. PREDICTIONS
# -------------------------------
y_pred_l2 = log_l2.predict(X_test_scaled)
y_prob_l2 = log_l2.predict_proba(X_test_scaled)[:,1]

y_pred_l1 = log_l1.predict(X_test_scaled)
y_prob_l1 = log_l1.predict_proba(X_test_scaled)[:,1]

y_pred_knn = knn_best.predict(X_test_scaled)
y_prob_knn = knn_best.predict_proba(X_test_scaled)[:,1]

y_pred_nb = nb_model.predict(X_test_scaled)
y_prob_nb = nb_model.predict_proba(X_test_scaled)[:,1]

# -------------------------------
# 10. COMPARISON
# -------------------------------
results = pd.DataFrame([
    get_metrics(y_test, y_pred_l2, y_prob_l2, "LogReg L2"),
    get_metrics(y_test, y_pred_l1, y_prob_l1, "LogReg L1"),
    get_metrics(y_test, y_pred_knn, y_prob_knn, f"KNN (k={best_k})"),
    get_metrics(y_test, y_pred_nb, y_prob_nb, "Naive Bayes")
])

print("\n📊 MODEL COMPARISON")
print(results.sort_values(by='F1-Score', ascending=False))

# -------------------------------
# 11. ROC CURVES
# -------------------------------
plt.figure(figsize=(8,6))

models = [
    ("LogReg L2", y_prob_l2),
    ("LogReg L1", y_prob_l1),
    (f"KNN (k={best_k})", y_prob_knn),
    ("Naive Bayes", y_prob_nb)
]

for name, prob in models:
    fpr, tpr, _ = roc_curve(y_test, prob)
    auc = roc_auc_score(y_test, prob)
    plt.plot(fpr, tpr, label=f"{name} (AUC={auc:.3f})")

plt.plot([0,1],[0,1],'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

# -------------------------------
# 12. CONFUSION MATRIX (BEST MODEL)
# -------------------------------
best_model_name = results.sort_values(by='F1-Score', ascending=False).iloc[0]['Model']

print(f"\n🏆 Best Model: {best_model_name}")

# -------------------------------
# 13. KNN PERFORMANCE PLOT
# -------------------------------
plt.figure(figsize=(8,5))
plt.plot(k_values, knn_scores, marker='o')
plt.title("KNN Accuracy vs K")
plt.xlabel("k")
plt.ylabel("Accuracy")
plt.grid()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score
import seaborn as sns
import pandas as pd

# Load dataset (using the diabetes dataset you mentioned)
df = pd.read_csv('/content/sample_data/diabetes.csv')
# Convert target to categorical (factor-like)
df['Outcome'] = df['Outcome'].astype('category')

print("\nUpdated Data Types:")
print(df.dtypes)
print(df['Outcome'].value_counts())
log_model = LogisticRegression(max_iter=5000, random_state=42, class_weight='balanced')
cols_with_zero = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

df[cols_with_zero] = df[cols_with_zero].replace(0, np.nan)

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')
X = df.drop('Outcome', axis=1)
y = df['Outcome']

X_imputed = imputer.fit_transform(X)

# Print dataset info
print(f"\nDataset shape: {df.shape}")
print(f"\nFirst 5 rows:")
print(df.head())

print(f"\nColumn names:")
print(df.columns.tolist())

print(f"\nClass distribution (Outcome):")
print(df['Outcome'].value_counts())

print(f"\nBasic statistics:")
print(df.describe())

# Check for missing values
print(f"\nMissing values:")
print(df.isnull().sum())

# Separate features and target (Outcome is the target column)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_imputed, y, test_size=0.3, random_state=42, stratify=y
)

# Scaling (important for Logistic Regression and KNN, Naive Bayes works with/without scaling)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ---- Logistic Regression ----
log_model = LogisticRegression(max_iter=5000, random_state=42)
log_model.fit(X_train_scaled, y_train)
y_pred_log = log_model.predict(X_test_scaled)

# ---- KNN ----
k_values = range(1, 16)
knn_test_acc = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    knn_test_acc.append(knn.score(X_test_scaled, y_test))

best_k = k_values[np.argmax(knn_test_acc)]

# Train best KNN
knn_best = KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X_train_scaled, y_train)
y_pred_knn = knn_best.predict(X_test_scaled)

# ---- Naive Bayes ----
nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)
y_pred_nb = nb_model.predict(X_test_scaled)

# ---- Performance Metrics ----
def get_metrics(y_true, y_pred, model_name):
    cm = confusion_matrix(y_true, y_pred)
    TN, FP, FN, TP = cm.ravel()

    sensitivity = TP / (TP + FN)  # same as recall
    specificity = TN / (TN + FP)

    return {
        'Model': model_name,
        'Accuracy': accuracy_score(y_true, y_pred),
        'Precision': precision_score(y_true, y_pred),
        'Recall (Sensitivity)': sensitivity,
        'Specificity': specificity,
        'F1-Score': f1_score(y_true, y_pred)
    }
from sklearn.metrics import roc_auc_score, roc_curve
y_prob_log = log_model.predict_proba(X_test_scaled)[:, 1]
y_prob_knn = knn_best.predict_proba(X_test_scaled)[:, 1]
y_prob_nb = nb_model.predict_proba(X_test_scaled)[:, 1]
metrics_log['ROC-AUC'] = roc_auc_score(y_test, y_prob_log)
metrics_knn['ROC-AUC'] = roc_auc_score(y_test, y_prob_knn)
metrics_nb['ROC-AUC'] = roc_auc_score(y_test, y_prob_nb)
plt.figure(figsize=(8,6))

for y_prob, label in [
    (y_prob_log, 'Logistic Regression'),
    (y_prob_knn, f'KNN (k={best_k})'),
    (y_prob_nb, 'Naive Bayes')
]:
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    auc = roc_auc_score(y_test, y_prob)
    plt.plot(fpr, tpr, label=f'{label} (AUC = {auc:.3f})')

plt.plot([0,1],[0,1],'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.grid(alpha=0.3)
plt.show()

log_l2 = LogisticRegression(penalty='l2', C=1.0, max_iter=5000, random_state=42)
log_l1 = LogisticRegression(penalty='l1', solver='liblinear', C=1.0, max_iter=5000, random_state=42)
log_l2.fit(X_train_scaled, y_train)
log_l1.fit(X_train_scaled, y_train)

y_pred_l2 = log_l2.predict(X_test_scaled)
y_pred_l1 = log_l1.predict(X_test_scaled)
metrics_l2 = get_metrics(y_test, y_pred_l2, 'LogReg L2')
metrics_l1 = get_metrics(y_test, y_pred_l1, 'LogReg L1')

y_prob_l2 = log_l2.predict_proba(X_test_scaled)[:,1]
y_prob_l1 = log_l1.predict_proba(X_test_scaled)[:,1]

metrics_l2['ROC-AUC'] = roc_auc_score(y_test, y_prob_l2)
metrics_l1['ROC-AUC'] = roc_auc_score(y_test, y_prob_l1)
metrics_log = get_metrics(y_test, y_pred_log, 'Logistic Regression')
metrics_knn = get_metrics(y_test, y_pred_knn, f'KNN (k={best_k})')
metrics_nb = get_metrics(y_test, y_pred_nb, 'Naive Bayes')

# Create comparison DataFrame
comparison_df = pd.DataFrame([metrics_log, metrics_knn, metrics_nb])
print("\n" + "="*60)
print("MODEL COMPARISON")
print("="*60)
print(comparison_df.to_string(index=False))

# ---- Confusion Matrices ----
cm_log = confusion_matrix(y_test, y_pred_log)
cm_knn = confusion_matrix(y_test, y_pred_knn)
cm_nb = confusion_matrix(y_test, y_pred_nb)

# Plot confusion matrices
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

sns.heatmap(cm_log, annot=True, fmt='d', cmap='Blues', ax=axes[0])
axes[0].set_title("Logistic Regression", fontsize=12, fontweight='bold')
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("Actual")
# Add labels for axes
axes[0].set_xticklabels(['No Diabetes', 'Diabetes'])
axes[0].set_yticklabels(['No Diabetes', 'Diabetes'])

sns.heatmap(cm_knn, annot=True, fmt='d', cmap='Greens', ax=axes[1])
axes[1].set_title(f"KNN (k={best_k})", fontsize=12, fontweight='bold')
axes[1].set_xlabel("Predicted")
axes[1].set_ylabel("Actual")
axes[1].set_xticklabels(['No Diabetes', 'Diabetes'])
axes[1].set_yticklabels(['No Diabetes', 'Diabetes'])

sns.heatmap(cm_nb, annot=True, fmt='d', cmap='Oranges', ax=axes[2])
axes[2].set_title("Naive Bayes", fontsize=12, fontweight='bold')
axes[2].set_xlabel("Predicted")
axes[2].set_ylabel("Actual")
axes[2].set_xticklabels(['No Diabetes', 'Diabetes'])
axes[2].set_yticklabels(['No Diabetes', 'Diabetes'])

plt.tight_layout()
plt.show()

# ---- Feature Importance Analysis ----
# Get feature names
feature_names = df.columns[:-1].tolist()

# Logistic Regression feature importance
feature_importances = log_model.coef_[0]
log_importance = pd.Series(np.abs(feature_importances), index=feature_names)
log_importance = log_importance.sort_values(ascending=False)

# KNN Permutation importance
from sklearn.inspection import permutation_importance
perm = permutation_importance(knn_best, X_test_scaled, y_test, n_repeats=10, random_state=42)
knn_importance = pd.Series(perm.importances_mean, index=feature_names).sort_values(ascending=False)

# Naive Bayes - mean difference between classes
nb_importance = pd.Series(np.abs(nb_model.theta_[1] - nb_model.theta_[0]), index=feature_names)
nb_importance = nb_importance.sort_values(ascending=False)

# Plot feature importances
fig, axes = plt.subplots(1, 3, figsize=(15, 6))

# Logistic Regression
log_importance.head(10).plot(kind='barh', ax=axes[0], color='blue')
axes[0].set_title("Logistic Regression\n(Top 10 Features)", fontsize=11, fontweight='bold')
axes[0].set_xlabel("Absolute Coefficient")
axes[0].invert_yaxis()

# KNN
knn_importance.head(10).plot(kind='barh', ax=axes[1], color='green')
axes[1].set_title(f"KNN (k={best_k})\n(Permutation Importance)", fontsize=11, fontweight='bold')
axes[1].set_xlabel("Permutation Importance")
axes[1].invert_yaxis()

# Naive Bayes
nb_importance.head(10).plot(kind='barh', ax=axes[2], color='orange')
axes[2].set_title("Naive Bayes\n(Mean Difference)", fontsize=11, fontweight='bold')
axes[2].set_xlabel("|Mean(Diabetes) - Mean(No Diabetes)|")
axes[2].invert_yaxis()

plt.tight_layout()
plt.show()

# ---- Detailed Classification Reports ----
print("\n" + "="*60)
print("DETAILED CLASSIFICATION REPORTS")
print("="*60)

print("\n=== LOGISTIC REGRESSION ===")
print(classification_report(y_test, y_pred_log, target_names=['No Diabetes', 'Diabetes']))

print("\n=== KNN (k={}) ===".format(best_k))
print(classification_report(y_test, y_pred_knn, target_names=['No Diabetes', 'Diabetes']))

print("\n=== NAIVE BAYES ===")
print(classification_report(y_test, y_pred_nb, target_names=['No Diabetes', 'Diabetes']))

# ---- Bar Chart Comparison ----
metrics_names = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
log_values = [metrics_log['Accuracy'], metrics_log['Precision'], metrics_log['F1-Score']]
knn_values = [metrics_knn['Accuracy'], metrics_knn['Precision'],  metrics_knn['F1-Score']]
nb_values = [metrics_nb['Accuracy'], metrics_nb['Precision'],  metrics_nb['F1-Score']]

x = np.arange(len(metrics_names))
width = 0.25

fig, ax = plt.subplots(figsize=(10, 6))

ax.set_ylabel('Score', fontsize=12)
ax.set_title('Model Performance Comparison - Diabetes Dataset', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(metrics_names)
ax.legend(loc='lower right')
ax.set_ylim([0, 1.05])
ax.grid(True, alpha=0.3, axis='y')

# Add value labels on bars


plt.tight_layout()
plt.show()

# ---- Summary Statistics ----
print("\n" + "="*60)
print("SUMMARY AND OBSERVATIONS")
print("="*60)

best_model = comparison_df.loc[comparison_df['F1-Score'].idxmax(), 'Model']
print(f"\n🏆 Best model based on F1-Score: {best_model}")

print("\n📊 Key Observations:")
print(f"• Logistic Regression: Accuracy = {metrics_log['Accuracy']:.4f}, F1 = {metrics_log['F1-Score']:.4f}")
print(f"• KNN (k={best_k}): Accuracy = {metrics_knn['Accuracy']:.4f}, F1 = {metrics_knn['F1-Score']:.4f}")
print(f"• Naive Bayes: Accuracy = {metrics_nb['Accuracy']:.4f}, F1 = {metrics_nb['F1-Score']:.4f}")

print("\n💡 Model Characteristics:")
print("• Logistic Regression: Linear model, interpretable, assumes linear decision boundary")
print(f"• KNN: Non-parametric, instance-based, uses {best_k} neighbors")
print("• Naive Bayes: Probabilistic, assumes feature independence, fast training")

# Optional: Show prediction probabilities for Naive Bayes
print("\n📈 Naive Bayes Class Probabilities (first 10 test samples):")
proba_nb = nb_model.predict_proba(X_test_scaled[:10])
for i, prob in enumerate(proba_nb):
    print(f"Sample {i+1}: No Diabetes={prob[0]:.3f}, Diabetes={prob[1]:.3f}")

# Additional analysis: KNN performance across different k values
plt.figure(figsize=(10, 6))
plt.plot(k_values, knn_test_acc, 'bo-', linewidth=2, markersize=8)
plt.xlabel('Number of Neighbors (k)', fontsize=12)
plt.ylabel('Test Accuracy', fontsize=12)
plt.title('KNN Performance vs Number of Neighbors', fontsize=14, fontweight='bold')
plt.grid(True, alpha=0.3)
plt.axhline(y=max(knn_test_acc), color='r', linestyle='--', alpha=0.5, label=f'Best Accuracy: {max(knn_test_acc):.3f}')
plt.axvline(x=best_k, color='g', linestyle='--', alpha=0.5, label=f'Best k: {best_k}')
plt.legend()
plt.tight_layout()
plt.show()

print(f"\n✅ Best k value: {best_k} with accuracy: {max(knn_test_acc):.4f}")